[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ernesto-gym"
authors = [{name = "Davide Salaorni", email = "davide.salaorni@polimi.it"}]
dynamic = ["version", "description"]
